#!/bin/bash

. /var/www/corelinux/tc-tools.sh

TC_VERS="4 6 7"
TC_VERS="4 5 6 7"
TC_MIRROR="http://repo.tinycorelinux.net/"

WEB_ROOT="/var/www"
TEST_PATH="tinycore-testing"

update_testing_lists() {
  local dir="${WEB_ROOT%%/}/${TEST_PATH%%/}";
  for d in $( find $dir/*/ -maxdepth 1 -type d -name x86* ); do
    # We should have x86 and x86_64 directories now
    [ -d $d/tcz ] || continue;
    ( cd $d/tcz;
      update_available_package_list "$d/tcz";
    );
  done;
}


#update_available_package_list "$1" 
#TC_VERS="6 7"
#set -x;
#download_tcz_lists "$TC_VERS" "$TC_MIRROR";
#update_md5s "$TC_VERS" "$TC_MIRROR";
#remove_failed_extensions "$TC_VERS";
#update_failed_extensions "$TC_VERS" "$TC_MIRROR";

update_testing_lists;
